### ISSUE TITLE
I couldn't certificate binaries on official site because of lack of GPG public key. サイト上で頒布しているバイナリの検証を行うためのGPG公開鍵が見当たらず、検証できない

### ISSUE THREAD

**Issue by darklie** [ranvis/putty#3]
https://www.ranvis.com/putty 上のバイナリの検証をsignatureを使って行いたいのですが、署名を行っているGPG公開鍵が見当たらないために検証を行うことができない状態です。
公開鍵を載せている場所がありましたらお教えいただけないでしょうか。
https://www.ranvis.com/doc/putty/man/pgpkeys.html 上の鍵はPuTTY公式の鍵へのリンクとなっているため、ranvis版のビルドには用いることができないため、困っております。

I would like to verify binaries on https://www.ranvis.com/putty . However, I couldn't find GPG public key which signed the binaries and verify them.
Could you tell us where to find GPG public key?
Keys on https://www.ranvis.com/doc/putty/man/pgpkeys.html is official PuTTY GPG public key, so it couldn't verify ranvis binaries.

**Comment by ranvis** [comment]
https://www.ranvis.com/1A799D29.pub.asc からどうぞ。
pgp.nic.ad.jp にあるつもりだったのですが、有効期限が切れていました。すみません。
ダウンロードページにも後日書いておきます。

**Comment by darklie** [comment]
確認行いました
ダウンロードページにも鍵があることを確認できたので閉じたいと思います
