### ISSUE TITLE
Terminalフォント使用時、絵文字を表示させるとAssertする

### ISSUE THREAD

**Issue by polygon0323** [ranvis/putty#4]
フォントをTerminalに設定している時、コンソールで絵文字(?)を表示させるとAssertしました。
MSゴシックでは発生しなかったので、フォント依存のようです。
オリジナル版では未確認です（すみません）

![image](https://user-images.githubusercontent.com/4208047/172856271-39f4585d-b159-45a2-8fd7-32c99a76f770.png)

PuTTY-0.77-ranvis 2022-05-29 64bit 
OS: Windows 10 21H2
接続先: Debian 10

**Comment by ranvis** [comment]
今のところ試した限り、こちらでは再現しません。
行番号から推測すると、画面の描画中に再描画が発生した雰囲気ですが、何ででしょうね。

**Comment by polygon0323** [comment]
ありがとうございます。ちゃんと検証せずissue立ててしまいすみません。
再現データを作ろうとしているのですが、今のところ上手くいっていません。
以下の時は100%発生するのですが、同じ内容の文字列をcatすると起きたり起きなかったりで…。

* 4バイトの絵文字（例えば🐧）を含む文字列
* tmux上のMuttで表示した時
* Terminal 10pt
* 該当の絵文字はハーフサイズの豆腐表示
* PuTTY 0.76以前では起きず

MSゴシックでは該当絵文字も正しく表示されて現象も発生しないため、表示できない絵文字があるとだめという気もしますが、回避方法もあり原因もよくわからないのでひとまず保留とさせてください。

**Comment by ranvis** [comment]
追記ありがとうございます。

本日ウェブサイト経由で報告があったのですが
"✉️" (U+2709 U+FE0F) を 文字コード UTF-8 (CJK)もしくはUTF-8系で"CJK用の文字幅を使用する"設定だとフォントに関係なく同じ個所で落ちるのを確認できました。

ご報告と完全に同じ件かわかりませんが、当方の~0.66~ 0.76や、0.77のオリジナル版、iceiv+putt GDI版では落ちないらしいので、こちらから調べてみたいと思います。

**Comment by ranvis** [comment]
修正版を作成しました。
https://github.com/ranvis/putty/releases/tag/ranvis-0.77-2

多分よくなっていると思うのですが、ご都合の良いときにお試しください。

**Comment by polygon0323** [comment]
ありがとうございます！
こちらで試した限り、今のところ現象は起きなくなっています。

**Comment by ranvis** [comment]
ご確認ありがとうございます。
修正版として公開しました。
